version: "3.6"
services:
  postgres:
    image: "mdillon/postgis"
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis"
    restart: always
    ports:
      - "6379:6379"

  api-gateway:
    build: ./api-gateway
    tty: true
    volumes:
      - "./api-gateway:/api-gateway"
    ports:
      - "9000:9000"
